# DOCKER COMPOSE CONFIGURATION
# This file uses the version 3 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-file-structure-and-examples

version: '3.8'

services:

  ## TOOLSUITE SERVICES

  butler:
    image: cf-toolsuite/cf-butler
    ports:
      - 8080:8080
    env_file:
      - ./config/butler.env
    links:
      - prometheus
      - butler-db
    environment:
      - SPRING_APPLICATION_NAME=butler
      - SPRING_PROFILES_ACTIVE=on-demand
      - SPRING_R2DBC_URL=r2dbc:mysql://butler-db:3306/cf-butler
      - SPRING_R2DBC_USERNAME=dbadmin
      - SPRING_R2DBC_PASSWORD=thunderb0lt!
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx3G -XX:MaxDirectMemorySize=1G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true

  archivist:
    image: cf-toolsuite/cf-archivist
    ports:
      - 8081:8081
    env_file:
      - ./config/archivist.env
    links:
      - archivist-db
      - discovery-service
      - prometheus
    environment:
      - CF_BASE-URL=http://hoover
      - SPRING_APPLICATION_NAME=archivist
      - SPRING_PROFILES_ACTIVE=on-demand
      - SPRING_R2DBC_URL=r2dbc:mysql://archivist-db:3306/cf-archivist
      - SPRING_R2DBC_USERNAME=dbadmin
      - SPRING_R2DBC_PASSWORD=thunderb0lt!
      - SERVER_PORT=8081
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx2G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  hoover:
    image: cf-toolsuite/cf-hoover
    ports:
      - 8082:8082
    links:
      - config-service
      - discovery-service
      - prometheus
    environment:
      - SPRING_APPLICATION_NAME=hoover
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - SERVER_PORT=8082
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx2G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true

  hoover-ui:
    image: cf-toolsuite/cf-hoover-ui
    ports:
      - 8083:8083
    links:
      - discovery-service
      - prometheus
    environment:
      - CF_BASE-URL=http://hoover
      - SPRING_APPLICATION_NAME=hoover-ui
      - SERVER_PORT=8083
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx2G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
