# DOCKER COMPOSE CONFIGURATION
# This file uses the version 3 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-file-structure-and-examples

version: '3.8'

services:

  ## TOOLSUITE SERVICES

  butler:
    image: cf-toolsuite/cf-butler
    ports:
      - 8080:8080
    env_file:
      - ./config/butler.env
    links:
      - prometheus
      - butler-db
    environment:
      - SPRING_APPLICATION_NAME=cf-butler
      - SPRING_PROFILES_ACTIVE=cloud,on-demand
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx3G -XX:MaxDirectMemorySize=1G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true

  archivist:
    image: cf-toolsuite/cf-archivist
    ports:
      - 8081:8081
    env_file:
      - ./config/archivist.env
    links:
      - prometheus
      - archivist-db
    environment:
      - SPRING_APPLICATION_NAME=cf-archivist
      - SPRING_PROFILES_ACTIVE=cloud,on-demand
      - SERVER_PORT=8081
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx2G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true

  hoover:
    image: cf-toolsuite/cf-hoover
    ports:
      - 8082:8082
    links:
      - hoover-config-service
      - discovery-service
      - prometheus
    environment:
      - SPRING_APPLICATION_NAME=cf-hoover
      - SPRING_PROFILES_ACTIVE=cloud,on-demand
      - SERVER_PORT=8082
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx2G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true

  hoover-ui:
    image: cf-toolsuite/cf-hoover-ui
    ports:
      - 8083:8083
    links:
      - discovery-service
      - prometheus
    environment:
      - SPRING_APPLICATION_NAME=cf-hoover-ui
      - SPRING_PROFILES_ACTIVE=cloud,on-demand
      - SERVER_PORT=8083
      - DOCKER_IP=$DOCKER_IP
      - JAVA_OPTS=-Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -Djava.security.egd=file:///dev/urandom -Xmx2G
      - JAVA_ARTIFACTS_FETCH_MODE=obtain-jars-from-runtime-metadata
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,jars,health,heapdump,threaddump,metrics,pom,scheduledtasks,loggers,mappings,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
